version: '3'

services:
  zookeeper:
    image: 'confluentinc/cp-zookeeper:latest'
    env_file:
      - env/.env-zoo

  kafka:
    image: 'confluentinc/cp-kafka:latest'
    ports:
      - "9092:9092"
      - "9093:9093"
    env_file:
      - env/.env-kafka

  clickhouse1:
    image: yandex/clickhouse-server:latest
    volumes:
      - ./etl/clickhouse/node1:/etc/clickhouse-server
      - ./etl/clickhouse/node1/db-init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    ports:
      - "8123:8123"
      - "9000:9000"
    depends_on:
      - zookeeper
    env_file:
#      - ./clickhouse/.env-ch
      - .env.example

  clickhouse2:
    image: yandex/clickhouse-server:latest
    volumes:
      - ./etl/clickhouse/node2:/etc/clickhouse-server
    depends_on:
      - zookeeper
    env_file:
#      - ./clickhouse/.env-ch
      - .env.example

  clickhouse3:
    image: yandex/clickhouse-server:latest
    volumes:
      - ./etl/clickhouse/node3:/etc/clickhouse-server
      - ./etl/clickhouse/node3/db-init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    depends_on:
      - zookeeper
    env_file:
#      - ./clickhouse/.env-ch
      - .env.example

  clickhouse4:
    image: yandex/clickhouse-server:latest
    volumes:
      - ./etl/clickhouse/node4:/etc/clickhouse-server
    depends_on:
      - zookeeper
    env_file:
#      - ./clickhouse/.env-ch
      - .env.example

