# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/permissions.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1aprotobuf/permissions.proto\x12\x0bpermissions\"/\n\x11PermissionRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\"5\n\x12PermissionResponse\x12\x0e\n\x06status\x18\x01 \x01(\x03\x12\x0f\n\x07user_id\x18\x02 \x01(\t2b\n\nPermission\x12T\n\x0f\x43heckPermission\x12\x1e.permissions.PermissionRequest\x1a\x1f.permissions.PermissionResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobuf.permissions_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _PERMISSIONREQUEST._serialized_start = 43
    _PERMISSIONREQUEST._serialized_end = 90
    _PERMISSIONRESPONSE._serialized_start = 92
    _PERMISSIONRESPONSE._serialized_end = 145
    _PERMISSION._serialized_start = 147
    _PERMISSION._serialized_end = 245
# @@protoc_insertion_point(module_scope)
